# Generated by Django 5.2.5 on 2025-10-16 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rainrecord',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='rainrecord',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
