# Generated by Django 5.2.7 on 2025-11-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_rainrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainrecord',
            name='time_range',
            field=models.CharField(choices=[('00-03', '00-03'), ('03-06', '03-06'), ('06-09', '06-09'), ('09-12', '09-12'), ('12-15', '12-15'), ('15-18', '15-18'), ('18-21', '18-21'), ('21-00', '21-00')], default='00-03', max_length=5),
        ),
    ]
